name: my_sarafu
description: Sarafu
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  permission_handler: ^9.2.0
  contacts_service: ^0.6.3
  bloc: ^8.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter
  hydrated_bloc: 9.0.0-dev.2
  intl: ^0.17.0
  logger: ^1.1.0
  path_provider: ^2.0.9
  settings_ui: ^2.0.2
  web3dart: ^2.3.5
  intl_phone_number_input: ^0.7.0
  sticky_grouped_list: ^2.1.0
  animations: ^2.0.2
  formz: ^0.4.1

flutter_icons:
  image_path: "assets/images/sarafu_logo.png"
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
