name: mysarafu
description: Cross-platform application for interacting with the Sarafu Network
version: 0.0.1+2
publish_to: none

environment:
  sdk: ">=2.16.0 <3.1.0"

dependencies:
  animations: ^2.0.3
  auto_size_text: ^3.0.0
  barcode_scan2: ^4.2.1
  bip39: ^1.0.6
  bloc: ^8.0.3
  contacts_service: ^0.6.3
  dart_bip32_bip44: ^0.2.0
  equatable: ^2.0.3
  firebase_core: ^1.19.2
  firebase_core_desktop: ^1.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_nano_ffi: ^2.0.0
  flutter_secure_storage: ^5.0.2
  formz: ^0.4.1
  get_it: ^7.2.0
  hydrated_bloc: 9.0.0-dev.2
  intl: ^0.17.0
  json_serializable: ^6.3.1
  local_auth: ^2.1.0
  logger: ^1.1.0
  mockito: ^5.2.0
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  phone_numbers_parser: ^5.0.5
  settings_ui: ^2.0.2
  shared_preferences: ^2.0.15
  sqflite: ^2.0.2+1
  sticky_grouped_list: ^3.0.0
  validators: ^3.0.0
  web3dart: 2.3.5

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf
  assets:
    - assets/images/
