// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvsq8j6a4KZNlUdIP7ub9dzQTpGoIB02Q',
    appId: '1:34199390450:web:a682ce36260261c323e86b',
    messagingSenderId: '34199390450',
    projectId: 'mysarafu',
    authDomain: 'mysarafu.firebaseapp.com',
    storageBucket: 'mysarafu.appspot.com',
    measurementId: 'G-4X3MWPZL8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ1ig-rm3eg99sd-Mp-ffyJ_dlPzjcPpE',
    appId: '1:34199390450:android:210b7d8c400dd0df23e86b',
    messagingSenderId: '34199390450',
    projectId: 'mysarafu',
    storageBucket: 'mysarafu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1KY8oyLcHJdw5rVq4iF3u5iE8pqijWKE',
    appId: '1:34199390450:ios:a5b31c54c3e45b8623e86b',
    messagingSenderId: '34199390450',
    projectId: 'mysarafu',
    storageBucket: 'mysarafu.appspot.com',
    iosClientId:
        '34199390450-qd449t3c3prrk4aorlso4lfqro4is91l.apps.googleusercontent.com',
    iosBundleId: 'com.grassecon.org.my-sarafu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1KY8oyLcHJdw5rVq4iF3u5iE8pqijWKE',
    appId: '1:34199390450:ios:86ca9f2e1ca6f38a23e86b',
    messagingSenderId: '34199390450',
    projectId: 'mysarafu',
    storageBucket: 'mysarafu.appspot.com',
    iosClientId:
        '34199390450-rbj37rpu103gjp8v1geuro3sqornbbce.apps.googleusercontent.com',
    iosBundleId: 'com.grassecon.org.mySarafu',
  );
}
